#=======================================================================================================================
         project(graphics_module VERSION 0.0.1 LANGUAGES CXX)
#=======================================================================================================================
     add_library(graphics_module)
#=======================================================================================================================
add_subdirectory(core)
#=======================================================================================================================
add_subdirectory(opengl) # TODO rename this to gl | also the namespace
#=======================================================================================================================